// front/src/components/PromptCard.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router';
import { Heart, MessageCircle, Star } from 'lucide-vue-next';
import UiCard from '@/components/ui/UiCard.vue';
import UiTag from '@/components/ui/UiTag.vue';
import type { Prompt } from '@/types/models';

defineProps<{
  prompt: Prompt;
}>();
</script>

<template>
  <UiCard interactive padding="md" as="article">
    <RouterLink
      :to="{ name: 'prompt-detail', params: { id: prompt.id } }"
      class="block rounded-[var(--aph-radius-lg)] outline-none ring-offset-2 ring-offset-[var(--aph-surface)] focus-visible:ring-2 focus-visible:ring-[var(--aph-primary)]"
    >
      <h2 class="text-lg font-semibold leading-snug tracking-tight text-[var(--aph-text)] line-clamp-2">
        {{ prompt.title }}
      </h2>
      <p
        v-if="prompt.summary"
        class="mt-2 text-sm leading-relaxed text-[var(--aph-text-muted)] line-clamp-2"
      >
        {{ prompt.summary }}
      </p>
      <div v-if="(prompt.tags || []).length" class="mt-3 flex flex-wrap gap-2">
        <UiTag v-for="t in prompt.tags" :key="t.id" small>
          {{ t.name }}
        </UiTag>
      </div>
      <div class="mt-4 flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-[var(--aph-text-subtle)]">
        <span v-if="prompt.author" class="font-medium text-[var(--aph-text-muted)]">
          {{ prompt.author.username }}
        </span>
        <span class="inline-flex items-center gap-1">
          <Heart class="h-3.5 w-3.5" aria-hidden="true" />
          {{ prompt.likeCount }}
        </span>
        <span class="inline-flex items-center gap-1">
          <Star class="h-3.5 w-3.5" aria-hidden="true" />
          {{ prompt.favoriteCount }}
        </span>
        <span class="inline-flex items-center gap-1">
          <MessageCircle class="h-3.5 w-3.5" aria-hidden="true" />
          {{ prompt.commentCount }}
        </span>
      </div>
    </RouterLink>
  </UiCard>
</template>

// front-glm/src/components/prompt/PromptCard.tsx
import React from 'react'
import { useNavigate } from 'react-router-dom'
import { Heart, Star, MessageCircle } from 'lucide-react'
import type { Prompt } from '../../types'
import { formatRelativeTime, formatCount } from '../../utils/format'
import Avatar from '../ui/Avatar'
import Badge from '../ui/Badge'

interface PromptCardProps {
  prompt: Prompt
}

export default function PromptCard({ prompt }: PromptCardProps) {
  const navigate = useNavigate()

  return (
    <article
      onClick={() => navigate(`/prompt/${prompt.id}`)}
      className="group bg-white rounded-2xl overflow-hidden shadow-card hover:shadow-card-hover transition-all duration-400 cursor-pointer hover:-translate-y-1"
    >
      {/* Cover Image */}
      <div className="relative h-48 overflow-hidden">
        <img
          src={prompt.image || `https://picsum.photos/seed/aiphub-${prompt.id}/800/500`}
          alt={prompt.title}
          className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/40 via-transparent to-transparent" />
        {/* Category badge */}
        <div className="absolute top-3 left-3">
          <Badge variant="active" size="sm">{prompt.category?.name || ''}</Badge>
        </div>
      </div>

      {/* Content */}
      <div className="p-5">
        {/* Title */}
        <h3 className="text-h3 font-semibold text-warm-950 mb-2 group-hover:text-warm-700 transition-colors line-clamp-1">
          {prompt.title}
        </h3>

        {/* Summary */}
        <p className="text-body-sm text-beige-700 mb-4 line-clamp-2 leading-relaxed">
          {prompt.summary || prompt.content.replace(/\n/g, ' ').slice(0, 100) + '...'}
        </p>

        {/* Tags */}
        {prompt.tags && prompt.tags.length > 0 && (
          <div className="flex flex-wrap gap-1.5 mb-4">
            {prompt.tags.slice(0, 3).map(tag => (
              <Badge key={tag.id} variant="muted" size="sm">{tag.name}</Badge>
            ))}
          </div>
        )}

        {/* Footer */}
        <div className="flex items-center justify-between pt-4 border-t border-beige-200/60">
          <div className="flex items-center gap-2">
            <Avatar src={prompt.author.avatar} username={prompt.author.username} size="sm" />
            <span className="text-body-sm text-warm-700">{prompt.author.username}</span>
            <span className="text-xs text-beige-600 ml-1">{formatRelativeTime(prompt.createTime)}</span>
          </div>
          <div className="flex items-center gap-3 text-beige-600">
            <span className="flex items-center gap-1 text-body-sm">
              <Heart className="w-4 h-4" />
              {formatCount(prompt.likeCount)}
            </span>
            <span className="flex items-center gap-1 text-body-sm">
              <Star className="w-4 h-4" />
              {formatCount(prompt.favoriteCount)}
            </span>
            <span className="flex items-center gap-1 text-body-sm hidden sm:flex">
              <MessageCircle className="w-4 h-4" />
              {prompt.commentCount}
            </span>
          </div>
        </div>
      </div>
    </article>
  )
}
