// front/src/features/prompt-hall/components/PromptCard.vue
<script setup lang="ts">
import type { PromptItem } from '@/shared/types/domain';

defineProps<{
  prompt: PromptItem;
  selected: boolean;
  secondCategoryName: string;
  thirdCategoryName: string;
}>();

const emit = defineEmits<{
  select: [promptId: number];
  toggleLike: [promptId: number];
  toggleFavorite: [promptId: number];
}>();
</script>

<template>
  <article class="card-shell" :class="{ 'card-selected': selected }" @click="emit('select', prompt.id)">
    <div class="card-media">
      <img class="card-image" :src="prompt.image || 'https://picsum.photos/seed/fallback-prompt/900/680'" :alt="prompt.title" />
      <div class="card-badges">
        <span>{{ secondCategoryName }}</span>
        <span>{{ thirdCategoryName }}</span>
      </div>
    </div>

    <div class="card-body">
      <div class="card-copy">
        <h3 class="card-title">{{ prompt.title }}</h3>
        <p class="card-summary">{{ prompt.summary || '这个 Prompt 暂无摘要，点击查看完整内容。' }}</p>
      </div>

      <div class="card-tags">
        <span v-for="tag in prompt.tags" :key="tag.id">{{ tag.name }}</span>
      </div>

      <div class="card-footer">
        <button class="metric-button" type="button" @click.stop="emit('toggleLike', prompt.id)">
          {{ prompt.liked ? '已赞' : '点赞' }} {{ prompt.likeCount }}
        </button>
        <button class="metric-button" type="button" @click.stop="emit('toggleFavorite', prompt.id)">
          {{ prompt.favorited ? '已藏' : '收藏' }} {{ prompt.favoriteCount }}
        </button>
        <span class="card-comments">评论 {{ prompt.commentCount }}</span>
      </div>
    </div>
  </article>
</template>

<style scoped>
.card-shell { display: grid; gap: 1rem; padding: 1rem; border-radius: 26px; border: 1px solid rgba(122, 93, 70, 0.12); background: rgba(255, 252, 247, 0.86); box-shadow: 0 16px 36px rgba(96, 68, 48, 0.08); cursor: pointer; transition: transform 180ms ease, box-shadow 180ms ease, border-color 180ms ease; }
.card-shell:hover { transform: translateY(-2px); box-shadow: 0 20px 42px rgba(96, 68, 48, 0.12); }
.card-selected { border-color: rgba(160, 117, 79, 0.46); box-shadow: 0 24px 48px rgba(135, 99, 69, 0.14); }
.card-media { position: relative; overflow: hidden; border-radius: 22px; aspect-ratio: 1.35; }
.card-image { width: 100%; height: 100%; object-fit: cover; }
.card-badges { position: absolute; inset: auto 0.8rem 0.8rem 0.8rem; display: flex; flex-wrap: wrap; gap: 0.5rem; }
.card-badges span,.card-tags span { padding: 0.34rem 0.65rem; border-radius: 999px; background: rgba(255, 249, 240, 0.88); color: var(--color-ink); font-size: 0.82rem; }
.card-body,.card-copy { display: grid; gap: 0.8rem; }
.card-title { margin: 0; font-family: var(--font-display); font-size: 1.4rem; line-height: 1.12; color: var(--color-ink); }
.card-summary { margin: 0; line-height: 1.7; color: var(--color-muted); }
.card-tags,.card-footer { display: flex; flex-wrap: wrap; gap: 0.7rem; align-items: center; }
.card-tags span { background: rgba(214, 188, 158, 0.16); color: var(--color-accent-strong); }
.metric-button,.card-comments { min-height: 40px; padding: 0 0.9rem; border-radius: 999px; border: 1px solid rgba(122, 93, 70, 0.12); background: rgba(255, 255, 255, 0.72); color: var(--color-ink); font-size: 0.88rem; }
.card-comments { display: inline-flex; align-items: center; }
</style>

// front-glm/src/components/prompt/PromptCard.tsx
import React from 'react'
import { useNavigate } from 'react-router-dom'
import { Heart, Star, MessageCircle } from 'lucide-react'
import type { Prompt } from '../../types'
import { formatRelativeTime, formatCount } from '../../utils/format'
import Avatar from '../ui/Avatar'
import Badge from '../ui/Badge'

interface PromptCardProps {
  prompt: Prompt
}

export default function PromptCard({ prompt }: PromptCardProps) {
  const navigate = useNavigate()

  return (
    <article
      onClick={() => navigate(`/prompt/${prompt.id}`)}
      className="group bg-white rounded-2xl overflow-hidden shadow-card hover:shadow-card-hover transition-all duration-400 cursor-pointer hover:-translate-y-1"
    >
      {/* Cover Image */}
      <div className="relative h-48 overflow-hidden">
        <img
          src={prompt.image || `https://picsum.photos/seed/aiphub-${prompt.id}/800/500`}
          alt={prompt.title}
          className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/40 via-transparent to-transparent" />
        {/* Category badge */}
        <div className="absolute top-3 left-3">
          <Badge variant="active" size="sm">{prompt.category?.name || ''}</Badge>
        </div>
      </div>

      {/* Content */}
      <div className="p-5">
        {/* Title */}
        <h3 className="text-h3 font-semibold text-warm-950 mb-2 group-hover:text-warm-700 transition-colors line-clamp-1">
          {prompt.title}
        </h3>

        {/* Summary */}
        <p className="text-body-sm text-beige-700 mb-4 line-clamp-2 leading-relaxed">
          {prompt.summary || prompt.content.replace(/\n/g, ' ').slice(0, 100) + '...'}
        </p>

        {/* Tags */}
        {prompt.tags && prompt.tags.length > 0 && (
          <div className="flex flex-wrap gap-1.5 mb-4">
            {prompt.tags.slice(0, 3).map(tag => (
              <Badge key={tag.id} variant="muted" size="sm">{tag.name}</Badge>
            ))}
          </div>
        )}

        {/* Footer */}
        <div className="flex items-center justify-between pt-4 border-t border-beige-200/60">
          <div className="flex items-center gap-2">
            <Avatar src={prompt.author.avatar} username={prompt.author.username} size="sm" />
            <span className="text-body-sm text-warm-700">{prompt.author.username}</span>
            <span className="text-xs text-beige-600 ml-1">{formatRelativeTime(prompt.createTime)}</span>
          </div>
          <div className="flex items-center gap-3 text-beige-600">
            <span className="flex items-center gap-1 text-body-sm">
              <Heart className="w-4 h-4" />
              {formatCount(prompt.likeCount)}
            </span>
            <span className="flex items-center gap-1 text-body-sm">
              <Star className="w-4 h-4" />
              {formatCount(prompt.favoriteCount)}
            </span>
            <span className="flex items-center gap-1 text-body-sm hidden sm:flex">
              <MessageCircle className="w-4 h-4" />
              {prompt.commentCount}
            </span>
          </div>
        </div>
      </div>
    </article>
  )
}
